/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsHistoryRouteImport } from './routes/bookings-history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEquipmentRouteImport } from './routes/admin.equipment'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSamplesRouteImport } from './routes/admin.samples'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ConfirmationBookingIdRouteImport } from './routes/confirmation.$bookingId'
import { Route as LabIdRouteImport } from './routes/lab.$id'
import { Route as PaymentSuccessBookingIdRouteImport } from './routes/payment-success.$bookingId'
import { Route as PaymentBookingIdRouteImport } from './routes/payment.$bookingId'
import { Route as PdiConfirmationRegistrationIdRouteImport } from './routes/pdi-confirmation.$registrationId'
import { Route as TrackBookingIdRouteImport } from './routes/track.$bookingId'
import { Route as TrackingBookingIdRouteImport } from './routes/tracking.$bookingId'
import { Route as WorkorderBookingIdRouteImport } from './routes/workorder.$bookingId'
import { Route as BookingLabIdServiceIdRouteImport } from './routes/booking.$labId.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsHistoryRoute = BookingsHistoryRouteImport.update({
  id: '/bookings-history',
  path: '/bookings-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipmentRoute = AdminEquipmentRouteImport.update({
  id: '/admin/equipment',
  path: '/admin/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSamplesRoute = AdminSamplesRouteImport.update({
  id: '/admin/samples',
  path: '/admin/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationBookingIdRoute = ConfirmationBookingIdRouteImport.update({
  id: '/confirmation/$bookingId',
  path: '/confirmation/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIdRoute = LabIdRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessBookingIdRoute = PaymentSuccessBookingIdRouteImport.update({
  id: '/payment-success/$bookingId',
  path: '/payment-success/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentBookingIdRoute = PaymentBookingIdRouteImport.update({
  id: '/payment/$bookingId',
  path: '/payment/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PdiConfirmationRegistrationIdRoute =
  PdiConfirmationRegistrationIdRouteImport.update({
    id: '/pdi-confirmation/$registrationId',
    path: '/pdi-confirmation/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrackBookingIdRoute = TrackBookingIdRouteImport.update({
  id: '/track/$bookingId',
  path: '/track/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingBookingIdRoute = TrackingBookingIdRouteImport.update({
  id: '/tracking/$bookingId',
  path: '/tracking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkorderBookingIdRoute = WorkorderBookingIdRouteImport.update({
  id: '/workorder/$bookingId',
  path: '/workorder/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingLabIdServiceIdRoute = BookingLabIdServiceIdRouteImport.update({
  id: '/booking/$labId/$serviceId',
  path: '/booking/$labId/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings-history': typeof BookingsHistoryRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/samples': typeof AdminSamplesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/lab/$id': typeof LabIdRoute
  '/payment-success/$bookingId': typeof PaymentSuccessBookingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/pdi-confirmation/$registrationId': typeof PdiConfirmationRegistrationIdRoute
  '/track/$bookingId': typeof TrackBookingIdRoute
  '/tracking/$bookingId': typeof TrackingBookingIdRoute
  '/workorder/$bookingId': typeof WorkorderBookingIdRoute
  '/booking/$labId/$serviceId': typeof BookingLabIdServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings-history': typeof BookingsHistoryRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/samples': typeof AdminSamplesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/lab/$id': typeof LabIdRoute
  '/payment-success/$bookingId': typeof PaymentSuccessBookingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/pdi-confirmation/$registrationId': typeof PdiConfirmationRegistrationIdRoute
  '/track/$bookingId': typeof TrackBookingIdRoute
  '/tracking/$bookingId': typeof TrackingBookingIdRoute
  '/workorder/$bookingId': typeof WorkorderBookingIdRoute
  '/booking/$labId/$serviceId': typeof BookingLabIdServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings-history': typeof BookingsHistoryRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/samples': typeof AdminSamplesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/lab/$id': typeof LabIdRoute
  '/payment-success/$bookingId': typeof PaymentSuccessBookingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/pdi-confirmation/$registrationId': typeof PdiConfirmationRegistrationIdRoute
  '/track/$bookingId': typeof TrackBookingIdRoute
  '/tracking/$bookingId': typeof TrackingBookingIdRoute
  '/workorder/$bookingId': typeof WorkorderBookingIdRoute
  '/booking/$labId/$serviceId': typeof BookingLabIdServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings-history'
    | '/dashboard'
    | '/notifications'
    | '/portal'
    | '/profile'
    | '/services'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/samples'
    | '/admin/settings'
    | '/confirmation/$bookingId'
    | '/lab/$id'
    | '/payment-success/$bookingId'
    | '/payment/$bookingId'
    | '/pdi-confirmation/$registrationId'
    | '/track/$bookingId'
    | '/tracking/$bookingId'
    | '/workorder/$bookingId'
    | '/booking/$labId/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings-history'
    | '/dashboard'
    | '/notifications'
    | '/portal'
    | '/profile'
    | '/services'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/samples'
    | '/admin/settings'
    | '/confirmation/$bookingId'
    | '/lab/$id'
    | '/payment-success/$bookingId'
    | '/payment/$bookingId'
    | '/pdi-confirmation/$registrationId'
    | '/track/$bookingId'
    | '/tracking/$bookingId'
    | '/workorder/$bookingId'
    | '/booking/$labId/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/bookings-history'
    | '/dashboard'
    | '/notifications'
    | '/portal'
    | '/profile'
    | '/services'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/samples'
    | '/admin/settings'
    | '/confirmation/$bookingId'
    | '/lab/$id'
    | '/payment-success/$bookingId'
    | '/payment/$bookingId'
    | '/pdi-confirmation/$registrationId'
    | '/track/$bookingId'
    | '/tracking/$bookingId'
    | '/workorder/$bookingId'
    | '/booking/$labId/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsHistoryRoute: typeof BookingsHistoryRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  PortalRoute: typeof PortalRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEquipmentRoute: typeof AdminEquipmentRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSamplesRoute: typeof AdminSamplesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ConfirmationBookingIdRoute: typeof ConfirmationBookingIdRoute
  LabIdRoute: typeof LabIdRoute
  PaymentSuccessBookingIdRoute: typeof PaymentSuccessBookingIdRoute
  PaymentBookingIdRoute: typeof PaymentBookingIdRoute
  PdiConfirmationRegistrationIdRoute: typeof PdiConfirmationRegistrationIdRoute
  TrackBookingIdRoute: typeof TrackBookingIdRoute
  TrackingBookingIdRoute: typeof TrackingBookingIdRoute
  WorkorderBookingIdRoute: typeof WorkorderBookingIdRoute
  BookingLabIdServiceIdRoute: typeof BookingLabIdServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings-history': {
      id: '/bookings-history'
      path: '/bookings-history'
      fullPath: '/bookings-history'
      preLoaderRoute: typeof BookingsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipment': {
      id: '/admin/equipment'
      path: '/admin/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AdminEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/samples': {
      id: '/admin/samples'
      path: '/admin/samples'
      fullPath: '/admin/samples'
      preLoaderRoute: typeof AdminSamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$bookingId': {
      id: '/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/confirmation/$bookingId'
      preLoaderRoute: typeof ConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$id': {
      id: '/lab/$id'
      path: '/lab/$id'
      fullPath: '/lab/$id'
      preLoaderRoute: typeof LabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success/$bookingId': {
      id: '/payment-success/$bookingId'
      path: '/payment-success/$bookingId'
      fullPath: '/payment-success/$bookingId'
      preLoaderRoute: typeof PaymentSuccessBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$bookingId': {
      id: '/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof PaymentBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdi-confirmation/$registrationId': {
      id: '/pdi-confirmation/$registrationId'
      path: '/pdi-confirmation/$registrationId'
      fullPath: '/pdi-confirmation/$registrationId'
      preLoaderRoute: typeof PdiConfirmationRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$bookingId': {
      id: '/track/$bookingId'
      path: '/track/$bookingId'
      fullPath: '/track/$bookingId'
      preLoaderRoute: typeof TrackBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$bookingId': {
      id: '/tracking/$bookingId'
      path: '/tracking/$bookingId'
      fullPath: '/tracking/$bookingId'
      preLoaderRoute: typeof TrackingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workorder/$bookingId': {
      id: '/workorder/$bookingId'
      path: '/workorder/$bookingId'
      fullPath: '/workorder/$bookingId'
      preLoaderRoute: typeof WorkorderBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$labId/$serviceId': {
      id: '/booking/$labId/$serviceId'
      path: '/booking/$labId/$serviceId'
      fullPath: '/booking/$labId/$serviceId'
      preLoaderRoute: typeof BookingLabIdServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsHistoryRoute: BookingsHistoryRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  PortalRoute: PortalRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEquipmentRoute: AdminEquipmentRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSamplesRoute: AdminSamplesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ConfirmationBookingIdRoute: ConfirmationBookingIdRoute,
  LabIdRoute: LabIdRoute,
  PaymentSuccessBookingIdRoute: PaymentSuccessBookingIdRoute,
  PaymentBookingIdRoute: PaymentBookingIdRoute,
  PdiConfirmationRegistrationIdRoute: PdiConfirmationRegistrationIdRoute,
  TrackBookingIdRoute: TrackBookingIdRoute,
  TrackingBookingIdRoute: TrackingBookingIdRoute,
  WorkorderBookingIdRoute: WorkorderBookingIdRoute,
  BookingLabIdServiceIdRoute: BookingLabIdServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
